import { expect, test } from "vitest";
import {
  ADJECTIVES,
  ANIMALS,
  generateName,
  hashPlayerId,
  validateName,
} from "./names";

test("generateName is deterministic for same input", () => {
  const a = generateName("abc-123");
  const b = generateName("abc-123");
  expect(a).toBe(b);
});

test("generateName produces the documented shape", () => {
  const name = generateName("some-random-uuid-value");
  expect(name).toMatch(/^[A-Z][a-z]+[A-Z][a-z]+\d{2}$/);
});

test("generateName varies across different playerIds", () => {
  const names = new Set<string>();
  for (let i = 0; i < 50; i++) {
    names.add(generateName(`player-${i}`));
  }
  expect(names.size).toBeGreaterThan(40);
});

test("generateName with suffix appends 2 hex chars after the number", () => {
  const base = generateName("abc-123");
  const bumped = generateName("abc-123", 1);
  expect(bumped).not.toBe(base);
  expect(bumped).toMatch(/^[A-Z][a-z]+[A-Z][a-z]+\d{2}[0-9a-f]{2}$/);
});

test("generateName suffix 1 vs 2 produces different extensions", () => {
  const a = generateName("abc-123", 1);
  const b = generateName("abc-123", 2);
  expect(a).not.toBe(b);
});

test("hashPlayerId is stable and non-zero for non-empty input", () => {
  expect(hashPlayerId("a")).toBe(hashPlayerId("a"));
  expect(hashPlayerId("a")).not.toBe(hashPlayerId("b"));
  expect(hashPlayerId("anything")).toBeGreaterThan(0);
});

test("ADJECTIVES and ANIMALS pools are exported and non-empty", () => {
  expect(ADJECTIVES.length).toBeGreaterThan(10);
  expect(ANIMALS.length).toBeGreaterThan(10);
});

test("validateName accepts a name built from the pools", () => {
  const name = `${ADJECTIVES[0]}${ANIMALS[0]}42`;
  expect(validateName(name)).toBe(true);
});

test("validateName accepts all values generated by generateName", () => {
  for (let i = 0; i < 20; i++) {
    expect(validateName(generateName(`p-${i}`))).toBe(true);
  }
});

test("validateName rejects names with bad format", () => {
  expect(validateName("")).toBe(false);
  expect(validateName("lowercaseOtter22")).toBe(false);
  expect(validateName("FestiveOtter2")).toBe(false); // only 1 digit
  expect(validateName("FestiveOtter")).toBe(false); // no digits
  expect(validateName("Festive-Otter22")).toBe(false); // bad char
});

test("validateName rejects adjective not in the pool", () => {
  expect(validateName("BogusOtter22")).toBe(false);
});

test("validateName rejects animal not in the pool", () => {
  expect(validateName(`${ADJECTIVES[0]}Bogus22`)).toBe(false);
});

test("validateName rejects suffix outside 10-99 range", () => {
  expect(validateName(`${ADJECTIVES[0]}${ANIMALS[0]}09`)).toBe(false);
});
